services:
  bootsik.testtask.webapi:
    image: bootsik.testtask.webapi
    build:
      context: .
      dockerfile: Bootsik.TestTask.WebApi/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      postgres:
        condition: service_healthy 

  postgres:
    image: postgres:17.6
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 5
